"""Persistence port for standalone PKB application/domain code.

The port exposes business-meaningful persistence operations. PostgreSQL driver
objects, cursors, SQL and JSONB are intentionally absent from this contract.
"""
from __future__ import annotations

from typing import Protocol
from uuid import UUID

from .correction_service import CorrectionResult
from .ingestion_gate import InputRecord, ProposedClaim
from .pending_service import PendingResult
from .query_service import ClaimPage, ClaimQuery
from .write_service import WriteResult


class PkbRepository(Protocol):
    def source_ref(self, prefix: str, identifier: str) -> str: ...

    def list_entities(self) -> list[dict]: ...
    def load_entity_detail(self, entity_id: str) -> dict | None: ...
    def list_components(self, parent_entity_id: UUID) -> list[dict]: ...
    def resolve_component_reference(
        self, parent_name: str, role_token: str
    ) -> dict | None: ...
    def authoritative_entity_aliases(self) -> dict[str, set[str]]: ...
    def load_catalog(self) -> list[dict]: ...

    def write_one(
        self, record: InputRecord, claim: ProposedClaim
    ) -> WriteResult: ...
    def correct_entity(
        self, record: InputRecord, claim: ProposedClaim
    ) -> CorrectionResult: ...
    def find_correction_targets(
        self, *, old_entity_id: str, predicate: str, value: str
    ) -> list[tuple]: ...

    def enqueue_pending(self, **kwargs) -> PendingResult: ...
    def list_pending(self, limit: int = 50) -> list[dict]: ...
    def accept_pending(self, pending_id: str) -> PendingResult: ...
    def review_pending(
        self, pending_id: str, decision: str
    ) -> PendingResult: ...
    def list_reviewed(self, limit: int = 20) -> list[dict]: ...

    def query_claims(self, query: ClaimQuery) -> ClaimPage: ...
    def write_intake(self, intake, *, extractor) -> dict: ...
